Update README.md
camaraproject/DeviceStatus pull request #139
Opened 2024-04-11 22:05 UTC by wrathwolf

Cleaned up README.md so that it is presentable for "GitHub Include" on the wiki

Also update community meeting registration / join link

2024-04-12 07:47 UTC, bigludo7 submitted a review, later dismissed
LGTM

2024-04-12 09:31 UTC, akoshunyadi approved these changes

2024-04-12 16:22 UTC, hdamker requested changes

2024-04-12 16:22 UTC, hdamker commented on README.md
>      - [View it on Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/release-0.5.1/code/API_definitions/device-status.yaml)
These information belongs still into a section status and released versions. The audience aren't (potential) contributors, but readers who want on the glance get the information about latest release etc. 

See also discussion/proposal in https://github.com/camaraproject/Template_Lead_Repository/pull/3

2024-04-12 16:22 UTC, hdamker commented on README.md
>      - [View it on Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/release-0.5.1/code/API_definitions/device-status.yaml)
These lines we might need to be only in CHANGELOG.md and the release notes in Github (to avoid that the README need to be updated with each release).

2024-04-12 16:22 UTC, hdamker commented on README.md
> +  * Release Information: Link to wiki
What is meant with "Release Information" within the wiki? The source of truth should be the CHANGELOG.md (and the release notes in https://github.com/camaraproject/DeviceStatus/releases, but that are direct copies from CHANGELOG.md, done at the creation of the release.

2024-04-12 16:24 UTC, hdamker commented
Please comment in https://github.com/camaraproject/Template_Lead_Repository/pull/3 regarding the upcoming structure for the README.md. That should be agreed before we touch all repositories.

2024-04-29 11:45 UTC, sachinvodafone approved these changes

2024-05-08 06:48 UTC, akoshunyadi commented
@hdamker @wrathwolf Can we merge this PR? Are we conform with the agreed format?

2024-05-08 09:03 UTC, hdamker commented
@akoshunyadi I have updated the README according to the template (moved the release information back into an own section). Megalinter is failing on unchanged files, I suppose that the branch need to be rebased?

2024-05-08 09:04 UTC, hdamker commented on README.md
>      - [View it on Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/release-0.5.1/code/API_definitions/device-status.yaml)
Addressed in https://github.com/camaraproject/DeviceStatus/pull/139/commits/16e59f107bc13d9fbe199a53369dee16aae1d6dd

2024-05-08 09:04 UTC, hdamker commented on README.md
>      - [View it on Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/release-0.5.1/code/API_definitions/device-status.yaml)
Kept in for now. Added comment in https://github.com/camaraproject/DeviceStatus/pull/139/commits/16e59f107bc13d9fbe199a53369dee16aae1d6dd that the lines can be omitted going forward.

2024-05-08 09:07 UTC, hdamker submitted a review, later dismissed
LGTM now :-)

2024-05-09 16:22 UTC, hdamker commented
> Don't we need the link to the meeting minutes?

@akoshunyadi you are right, missed that line from the template. Added with https://github.com/camaraproject/DeviceStatus/pull/139/commits/efd99cb002e9a172cfdf61478e513e8b30d55022

(will leave approval and merge now to the Sub Project ... had approved before only to get my blocking comments out of the way)

2024-05-10 06:34 UTC, bigludo7 approved these changes

2024-05-10 07:22 UTC, akoshunyadi approved these changes

2024-05-13 13:27 UTC, merged