Prepare release r0.7
camaraproject/DeviceStatus pull request #190
Opened 2024-07-15 13:23 UTC by akoshunyadi

#### What type of PR is this?

* subproject management

#### What this PR does / why we need it:

Prepare the release 0.7.

#### Which issue(s) this PR fixes:

#### Special notes for reviewers:

#### Changelog input

#### Additional documentation

2024-07-18 08:42 UTC, hdamker commented
@akoshunyadi Could you please change the release number to r1.1? See "API release numbers start at r1.1" within https://github.com/camaraproject/ReleaseManagement/blob/main/documentation/API_Release_Guidelines.md 

I know that the sub project have done a release r0.6 previously, but now it is time to start into the numbering of the Fall24 release cycle ;-) r1.2 could also be an option, to show that it is already the second release within the current cycle.

2024-07-23 11:42 UTC, hdamker commented on README.md
> +    - [View it on Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/r1.1/code/API_definitions/device-status.yaml)
There is no device-status.yaml anymore ... how about the following (lot of source code, but looks quite nice when rendered):

```suggestion
The release r1.1 contains the following API definitions (with inline documentation):
- device-roaming-status [[YAML]](https://github.com/camaraproject/DeviceStatus/blob/r1.1/code/API_definitions/device-roaming-status.yaml)
[[View it on ReDoc]](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/r1.1/code/API_definitions/device-roaming-status.yaml&nocors)
[[View it on Swagger Editor]](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/r1.1/code/API_definitions/device-roaming-status.yaml)
- device-roaming-status-subscriptions [[YAML]](https://github.com/camaraproject/DeviceStatus/blob/r1.1/code/API_definitions/device-roaming-status-subscriptions.yaml)
[[View it on ReDoc]](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/r1.1/code/API_definitions/device-roaming-status-subscriptions.yaml&nocors)
[[View it on Swagger Editor]](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/r1.1/code/API_definitions/device-roaming-status-subscriptions.yaml)
- device-reachability-status [[YAML]](https://github.com/camaraproject/DeviceStatus/blob/r1.1/code/API_definitions/device-reachability-status.yaml)
[[View it on ReDoc]](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/r1.1/code/API_definitions/device-reachability-status.yaml&nocors)
[[View it on Swagger Editor]](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/r1.1/code/API_definitions/device-reachability-status.yaml)
- device-reachability-status-subscriptions [[YAML]](https://github.com/camaraproject/DeviceStatus/blob/r1.1/code/API_definitions/device-reachability-status-subscriptions.yaml)
[[View it on ReDoc]](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/r1.1/code/API_definitions/device-reachability-status-subscriptions.yaml&nocors)
[[View it on Swagger Editor]](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/DeviceStatus/r1.1/code/API_definitions/device-reachability-status-subscriptions.yaml)
```

BTW a hint: if you create temporarily a branch `r1.1` you can test the links ... you just need to delete it before you can create the tag ;-)

2024-07-23 11:43 UTC, hdamker commented on CHANGELOG.md
> +- [r1.1](#r07)
```suggestion
- [r1.1](#r11)
```

2024-07-24 16:04 UTC, bigludo7 submitted a review, later dismissed
LGTM

2024-07-24 18:21 UTC, hdamker commented
@akoshunyadi consider to add @camaraproject/release-management_maintainers as reviewers if the PR is there.

2024-07-24 18:43 UTC, akoshunyadi commented
> @akoshunyadi consider to add @camaraproject/release-management_maintainers as reviewers if the PR is there.

yes, I would wait until all PRs are merged, and the change-log is final

2024-07-26 07:28 UTC, bigludo7 approved these changes
LGTM

2024-07-26 15:32 UTC, hdamker requested changes
@akoshunyadi Done the review on behalf of Release Management in context of https://github.com/camaraproject/ReleaseManagement/issues/57

Still found some points ;-) 

Please update also the release tracker pages at https://wiki.camaraproject.org/display/CAM/DeviceStatus+API+Release+Tracking

2024-07-26 16:00 UTC, akoshunyadi commented on CHANGELOG.md
> +* for each first alpha or release-candidate API version, all changes since the release of the previous public API version
I understood this like the alpha release was the first, which had all changes and this is the 2nd release of the v0.6....
But I can add the issues here too.

2024-07-26 16:03 UTC, akoshunyadi commented on code/API_definitions/device-reachability-status-subscriptions.yaml
> +  version: 0.6.0-rc.1
sure, I have never heard about it so far :-)

2024-07-26 17:29 UTC, hdamker approved these changes
LGTM from ReleaseManagement view - suppose we are done here.

@camaraproject/device-status_codeowners  the PR needs a new codeowner review before it can be merged

2024-07-31 07:45 UTC, maxl2287 approved these changes
LGTM

2024-07-31 09:20 UTC, eric-murray commented on CHANGELOG.md
> +Note: the previous device-status API with roaming and connectivity endpoints has been splitted into 4 specific APIs
```suggestion
Note: the previous device-status API with roaming and connectivity endpoints has been split into 4 specific APIs
```

2024-07-31 09:36 UTC, eric-murray commented
Github is not letting me make suggestions for the "Scope" section in the README, but I'd suggest putting the different functions in different bullet points. e.g.:

* It provides the customer with the ability to:  
  * check if a device is reachable or has lost connection to the network
  * check the roaming status of a device, and which network it is roaming on
  * receive notifications if the status of the device changes

2024-07-31 13:11 UTC, hdamker commented
> Github is not letting me make suggestions for the "Scope" section in the README, but I'd suggest putting the different functions in different bullet points

The reason is that these lines are not changed by the PR. As this is also not within the scope of this PR, how about propose it in an issue and address, when some more Codeowners are again available? (it can perfectly done between RC and public release)

2024-07-31 15:46 UTC, eric-murray approved these changes

2024-08-02 06:33 UTC, merged