Update MAINTAINERS.MD
camaraproject/DeviceStatus pull request #3
Opened 2022-08-26 13:39 UTC by JoachimDahlgren

Signing up. Adding my name to the MAINTAINERS.MD

2022-09-23 10:14 UTC, jordonezlucena approved these changes

2022-10-07 09:29 UTC, eric-murray approved these changes

2022-11-07 08:45 UTC, monamok requested changes

2022-11-07 08:45 UTC, monamok commented on MAINTAINERS.MD
>  | Telefonica | Jose A Ordonez Lucena |
```suggestion
| Telefonica | Jose A Ordonez Lucena |
| Telefonica | Mona Mokhber |
```

2022-11-18 07:25 UTC, MarkusKuemmerle commented
José Ordonez asked me to change the TEF maintainers to Mona Mokhber and Jesus Pena. I'll merge this PR and change the TEF maintainers to that if necessary

2022-11-18 07:25 UTC, merged